
export enum PlayerMovementState {
    ROLLING = 'ROLLING',
    PENDING_JUMP = 'PENDING_JUMP',
    PENDING_ATTACK = 'PENDING_ATTACK',
    JUMPING = 'JUMPING',
    ATTACKING = 'ATTACKING',
    BACK_STEPPING = 'BACK_STEPPING',
    RUNNING = 'RUNNING',
    COOLDOWN = 'COOLDOWN',
}
